# Generated by Django 3.2.7 on 2022-01-22 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
