# Generated by Django 3.2.7 on 2022-01-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_academicyear_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_academic_year', to=settings.AUTH_USER_MODEL),
        ),
    ]
