# Generated by Django 3.2.7 on 2022-01-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_academic_year_academicyear_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_academic_year', to='school.school'),
        ),
    ]
