# Generated by Django 3.2.7 on 2022-01-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_academicyear_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='school.academicyear'),
        ),
    ]
