# Generated by Django 3.2.7 on 2022-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
