# Generated by Django 3.2.7 on 2022-01-21 19:57

from django.db import migrations, models
import django.utils.timezone
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(blank=True, default=user.models.gen_id, max_length=255, null=True, verbose_name='user id')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='gender')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('role', models.CharField(blank=True, default={('MANAGER', 'MANAGER'), ('TEACHER', 'TEACHER'), ('HR', 'HR'), ('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT')}, max_length=255, null=True, verbose_name='role')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='profile image')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'ordering': ('-date_joined',),
            },
        ),
    ]
